version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_DB=job
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - job_mvp_pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=80
    ports:
      - "7070:80"
    depends_on:
      - postgres
    volumes:
      - job_mvp_pgadmin_data:/var/lib/pgadmin

  backend:
    image: umesh2645/job_mvp_backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings:pg=Host=postgres;Port=5432;Database=job;Username=myuser;Password=mypassword;
    ports:
      - "7071:8080"
    depends_on:
      - postgres

  frontend:
    image: umesh2645/job_mvp_frontend
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    environment:
      NODE_ENV: production
      REACT_APP_BASE_URL: backend/api
    ports:
      - 3000:3000

volumes:
  job_mvp_pg_data:
  job_mvp_pgadmin_data:
