apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-mvp-backend
  namespace: job-mvp-ns
  labels:
    app: job-mvp-backend
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: job-mvp-backend
      tier: backend
  template:
    metadata:
      labels:
        app: job-mvp-backend
        tier: backend
    spec:
      containers:
        - name: job-mvp-backend
          image: umesh2645/job_mvp_backend
          imagePullPolicy: IfNotPresent
          ports:
            - name: http-server
              containerPort: 8080
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 512Mi
              cpu: "0.2"
          env:
            - name: PORT
              value: "8080"
            - name: ConnectionStrings__pg
              # value: Host=job-mvp-postgres-svc.job-mvp-ns.svc.cluster.local;Port=5432;Database=job;Username=myuser;Password=mypassword;
              value: Host=job-mvp-backend-svc;Port=5432;Database=job;Username=myuser;Password=mypassword;
---
apiVersion: v1
kind: Service
metadata:
  name: job-mvp-backend-svc
  namespace: job-mvp-ns
  labels:
    app: job-mvp-backend-svc
    tier: backend
spec:
  type: NodePort
  selector:
    app: job-mvp-backend-svc
    tier: backend
  ports:
    - port: 8080
      targetPort: http-server
