apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: job-mvp-ns
spec:
  selector:
    matchLabels:
      app: job-mvp-frontend
      tier: frontend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: job-mvp-frontend
        tier: frontend
        track: stable
    spec:
      containers:
      - name: frontend
        image: umesh2645/job_mvp_frontend
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 512Mi
            cpu: "0.2"
---
apiVersion: v1
kind: Service
metadata:
  name: job-mvp-frontend-svc
  namespace: job-mvp-ns
spec:
  selector:
    app: job-mvp-frontend
    tier: frontend
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
    nodePort: 30004
  type: NodePort
