apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-job_mvp-frontend
  labels:
    app: dotnet-job_mvp
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dotnet-job_mvp
      tier: frontend
  template:
    metadata:
      labels:
        app: dotnet-job_mvp
        tier: frontend
    spec:
      containers:
        - name: frontend
          image: dotnet-job_mvp-frontend
          imagePullPolicy: IfNotPresent
          ports:
            - name: http-server
              containerPort: 8080
            - name: debug
              containerPort: 9229
          env:
            - name: PORT
              value: "8080"
            - name: job_mvp_API_ADDR
              value: dotnet-job_mvp-backend
---
apiVersion: v1
kind: Service
metadata:
  name: dotnet-job_mvp-frontend
  labels:
    app: dotnet-job_mvp
    tier: frontend
spec:
  type: NodePort
  selector:
    app: dotnet-job_mvp
    tier: frontend
  ports:
    - port: 80
      targetPort: http-server
